from pathlib import Path
from getpass import getpass
import json
import httpx
from urllib.parse import urlparse

folder = Path(__file__).resolve().parent
url = input('Kaggle HTTPS API URL: ').strip().rstrip('/')
parsed = urlparse(url)
if parsed.scheme != 'https' or not parsed.hostname or parsed.username or parsed.password or parsed.query or parsed.fragment:
    raise SystemExit('Enter the HTTPS tunnel URL only.')
token = getpass('API_TOKEN (hidden; paste from your own Kaggle notebook): ').strip()
if len(token) < 32:
    raise SystemExit('Token is too short. Use the API_TOKEN generated by the startup cell.')
try:
    response = httpx.get(url + '/health', headers={'Authorization':'Bearer ' + token}, timeout=30, follow_redirects=False)
except httpx.HTTPError:
    raise SystemExit('Cannot connect. Check the URL and keep Kaggle running.')
if response.status_code != 200:
    raise SystemExit('Connection rejected. Check the URL and token.')
(folder / '.env').write_text('VISIONFIND_API_URL=' + json.dumps(url) + '\nVISIONFIND_API_TOKEN=' + json.dumps(token) + '\n')
print('Connection verified. Start the interface with: python run.py')
